### ISSUE TITLE
How Can I Stop Calibre from Merging Metadata?

### ISSUE THREAD

**Issue by DoiiarX** [confluence/isfdb2-calibre#5]
I am also a developer for [a calibre plugin](https://github.com/DoiiarX/NLCISBNPlugin), but I'm unsure about how to save multiple results.

I came across your article here: https://www.mobileread.com/forums/showthread.php?t=340056. I am curious to know if there is a method to achieve this without having to enable the `several entries per source` option?

**Comment by confluence** [comment]
Hello! That's not me; that's [this person, who forked my fork](https://github.com/confluence/isfdb2-calibre/pull/4). :)

I deal with this issue by looking up results in a very specific way, with some up-front manual work in a browser. It's described [here](http://confluence.locustforge.net/blog/posts/isfdb-calibre/). In summary, I first find specific matches on ISFDB, which are as close to the edition I have as possible, then I use a script to inspect my running Firefox instance's tabs to find all the relevant ones and output the unique ISFDB publication IDs, then I pipe those to a script which creates blank Calibre entries containing only those identifiers, then I open Calibre and fetch metadata for those entries with _only_ my plugin enabled. Internally, my plugin returns only one result per entry if a publication ID is present, because it directly fetches that page and scrapes it (otherwise it behaves like other plugins and searches for the other fields and may return multiple results).

You may be able to implement similar behaviour in your plugin, if there is a unique ID that you can use for a specific publication (ISBN does not uniquely identify a publication) -- does the library website have a unique ID per publication? But you would still need to disable other plugins while fetching metadata, otherwise you would still be getting additional results from those other plugins. As far as I know there is no way to disable Calibre's built-in metadata merging, and the Calibre developer has no intention of adding one.

**Comment by DoiiarX** [comment]
> Hello! That's not me; that's [this person, who forked my fork](https://github.com/confluence/isfdb2-calibre/pull/4). :)
> 
> I deal with this issue by looking up results in a very specific way, with some up-front manual work in a browser. It's described [here](http://confluence.locustforge.net/blog/posts/isfdb-calibre/). In summary, I first find specific matches on ISFDB, which are as close to the edition I have as possible, then I use a script to inspect my running Firefox instance's tabs to find all the relevant ones and output the unique ISFDB publication IDs, then I pipe those to a script which creates blank Calibre entries containing only those identifiers, then I open Calibre and fetch metadata for those entries with _only_ my plugin enabled. Internally, my plugin returns only one result per entry if a publication ID is present, because it directly fetches that page and scrapes it (otherwise it behaves like other plugins and searches for the other fields and may return multiple results).
> 
> You may be able to implement similar behaviour in your plugin, if there is a unique ID that you can use for a specific publication (ISBN does not uniquely identify a publication) -- does the library website have a unique ID per publication? But you would still need to disable other plugins while fetching metadata, otherwise you would still be getting additional results from those other plugins. As far as I know there is no way to disable Calibre's built-in metadata merging, and the Calibre developer has no intention of adding one.

thanks, i have solved
